{% set name = "csbdeep" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/csbdeep-{{ version }}.tar.gz
  sha256: 26880076f1ed4546964b94c7b59b7e8cffe3d028ae0ddbdb82f039df5b8a3eb7

build:
  noarch: python
  entry_points:
    - care_predict = csbdeep.scripts.care_predict:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - h5py >=3
    - tensorflow >=2.4  
    - matplotlib-base
    - numpy
    - python >=3.6
    - scipy
    - six
    - tifffile
    - tqdm
    - packaging

test:
  imports:
    - csbdeep
  commands:
    - pip list
    # - pip check
    - care_predict --help
  requires:
    - pip

about:
  home: http://csbdeep.bioimagecomputing.com/
  summary: CSBDeep - a toolbox for Content-aware Image Restoration (CARE)
  license: BSD-3-Clause
  license_file: LICENSE.txt
  dev_url: https://github.com/CSBDeep/CSBDeep
  doc_url: http://csbdeep.bioimagecomputing.com/doc/

extra:
  recipe-maintainers:
    - goanpeca
    - uschmidt83
