{% set name = "csbdeep" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/csbdeep-{{ version }}.tar.gz
  sha256: 8a000eb71d04aa753f52ffe81a34c0a30a06ee986d20b9986d76272253e2fd53

build:
  entry_points:
    - care_predict = csbdeep.scripts.care_predict:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - h5py >=3  # [py>=39]
    - h5py <3   # [py<39]
    - tensorflow >=2  # [unix]
    - matplotlib-base
    - numpy
    - python
    - scipy
    - six
    - tifffile
    - tqdm
    - packaging
  run_constrained:   # [win]
    - tensorflow >=2  # [win]

test:
  imports:
    - csbdeep
  commands:
    - pip list
    # - pip check
    - care_predict --help
  requires:
    - pip

about:
  home: http://csbdeep.bioimagecomputing.com/
  summary: CSBDeep - a toolbox for Content-aware Image Restoration (CARE)
  license: BSD-3-Clause
  license_file: LICENSE.txt
  dev_url: https://github.com/CSBDeep/CSBDeep
  doc_url: http://csbdeep.bioimagecomputing.com/doc/

extra:
  recipe-maintainers:
    - goanpeca
    - uschmidt83
