{% set name = "csbdeep" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/csbdeep-{{ version }}.tar.gz
  sha256: 85d6fc360bb33253ba6f543d75cf0cf123595f0ea4dd1fa76b1e5bc8fc55b901

build:
  entry_points:
    - care_predict = csbdeep.scripts.care_predict:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - tensorflow >=2  # [unix]
    - matplotlib-base
    - numpy
    - python
    - scipy
    - six
    - tifffile
    - tqdm
    - packaging
  run_constrained:   # [win]
    - tensorflow >=2  # [win]

test:
  imports:
    - csbdeep
  commands:
    - pip list
    # - pip check
    - care_predict --help
  requires:
    - pip

about:
  home: http://csbdeep.bioimagecomputing.com/
  summary: CSBDeep - a toolbox for Content-aware Image Restoration (CARE)
  license: BSD-3-Clause
  license_file: LICENSE.txt
  dev_url: https://github.com/CSBDeep/CSBDeep
  doc_url: http://csbdeep.bioimagecomputing.com/doc/

extra:
  recipe-maintainers:
    - goanpeca
    - uschmidt83
